name: restaurant
description: A new Flutter project.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=2.17.6 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter:

  assets:
     - assets/login.png
     - assets/menu.png
     - assets/reserva.png
     - assets/sedes.png
     - assets/hamburguesa.jpg
     - assets/order.png

  fonts:
     - family: Khand
       fonts:
         - asset: fonts/Khand-Bold.ttf
         - asset: fonts/Khand-Light.ttf
           style: italic
           weight: 700
  uses-material-design: true